# Generated by Django 4.2.9 on 2025-01-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinemaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardEventList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_lists/')),
                ('events', models.ManyToManyField(related_name='event_lists', to='Cinemaapp.event')),
            ],
        ),
    ]
