# Generated by Django 4.2.9 on 2025-01-19 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cinemaapp', '0003_event_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zaal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('events', models.ManyToManyField(related_name='zaals', to='Cinemaapp.event')),
                ('films', models.ManyToManyField(related_name='zaals', to='Cinemaapp.movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='zaal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='Cinemaapp.zaal'),
        ),
        migrations.AddField(
            model_name='standardeventlist',
            name='zaal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_lists', to='Cinemaapp.zaal'),
        ),
    ]
