# Generated by Django 4.2.9 on 2025-01-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinemaapp', '0005_remove_standardeventlist_zaal_event_zaal'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='movies/'),
        ),
    ]
