# Generated by Django 4.2.9 on 2025-01-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinemaapp', '0006_movie_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('info', models.TextField(verbose_name='Informatie')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Afbeelding')),
            ],
        ),
    ]
