# Generated by Django 4.2.9 on 2025-01-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinemaapp', '0008_alter_info_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Titel'),
        ),
    ]
