# Generated by Django 4.2.9 on 2025-01-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinemaapp', '0009_alter_info_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='info',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
