# Generated by Django 4.2.9 on 2025-01-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinemaapp', '0011_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.TextField(default='lammenschans'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='movies', to='Cinemaapp.location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='location_photos/'),
        ),
    ]
