# Generated by Django 4.2.9 on 2025-01-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinemaapp', '0012_location_address_movie_locations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
