# Generated by Django 4.2.9 on 2025-01-25 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cinemaapp', '0019_ticket_status_alter_ticket_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('seats', models.PositiveIntegerField()),
                ('is_vip', models.BooleanField(default=False)),
                ('zaal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='Cinemaapp.zaal')),
            ],
        ),
    ]
