# Generated by Django 4.2.9 on 2025-01-25 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cinemaapp', '0023_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
    ]
