# Generated by Django 4.2.9 on 2025-01-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinemaapp', '0024_remove_ticket_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='chair',
            new_name='seat',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_type',
        ),
        migrations.AddField(
            model_name='ticket',
            name='row',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('child', 'Child'), ('teen', 'Teen'), ('adult', 'Adult')], default='adult', max_length=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='vip',
            field=models.BooleanField(default=False),
        ),
    ]
