# Generated by Django 4.2.9 on 2025-01-26 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cinemaapp', '0025_rename_chair_ticket_seat_remove_ticket_ticket_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='showtime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='Cinemaapp.showtime'),
        ),
    ]
