# Generated by Django 4.2.9 on 2025-01-26 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cinemaapp', '0027_ticket_zaal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='chair',
            new_name='seat',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_type',
        ),
        migrations.AddField(
            model_name='reservation',
            name='row',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='showtime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='Cinemaapp.showtime'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='type',
            field=models.CharField(choices=[('child', 'Child'), ('teen', 'Teen'), ('adult', 'Adult')], default='adult', max_length=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='zaal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='Cinemaapp.zaal'),
        ),
    ]
