# Generated by Django 4.2.9 on 2025-01-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinemaapp', '0029_reservation_guest_email_reservation_guest_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
